### ISSUE TITLE
patients without SSIN

### ISSUE THREAD

**Issue by thibaultmh** [hl7-be/hl7-be-fhir-laboratory-report#107] opened 2022-03-03 08:12 UTC
Hi,

How should patients without a SSIN be handled? Do we use a local identifier?

Best,
Thibault

**Comment by bdc-ehealth** [comment] 2022-03-08 13:55
A local identifier seems the obvious choice.

**Comment by bdc-ehealth** [comment] 2022-03-15 15:11
This is a duplicate of #19

**Closed** 2022-03-15 15:11 UTC
